from datetime import datetime
from pydantic import BaseModel, Field


class ReadingBase(BaseModel):
    date: datetime = Field(...)
    total_power: float = Field(...)
    total_reactive_power: float = Field(...)
    total_apparent_power: float = Field(...)
    power_l1: float = Field(...)
    power_l2: float = Field(...)
    power_l3: float = Field(...)
    reactive_power_l1: float = Field(...)
    reactive_power_l2: float = Field(...)
    reactive_power_l3: float = Field(...)
    voltage_13: float = Field(...)
    voltage_12: float = Field(...)
    voltage_23: float = Field(...)
    voltage_l1: float = Field(...)
    voltage_l2: float = Field(...)
    voltage_l3: float = Field(...)
    current_l1: float = Field(...)
    current_l2: float = Field(...)
    current_l3: float = Field(...)
    current_n: float = Field(...)
    frequency: float = Field(...)
    total_cos: float = Field(...)
    cos_l1: float = Field(...)
    cos_l2: float = Field(...)
    cos_l3: float = Field(...)
    input_ea: float = Field(...)
    return_ea: float = Field(...)
    ind_eq: float = Field(...)
    cap_eq: float = Field(...)
    power_dc: float = Field(...)
    voltage_dc: float = Field(...)
    current_dc: float = Field(...)
    power_inv: float = Field(...)
    reactive_power_inv: float = Field(...)
    apparent_power_inv: float = Field(...)
    voltage_uab_inv: float = Field(...)
    voltage_ubc_inv: float = Field(...)
    voltage_uca_inv: float = Field(...)
    voltage_ua_inv: float = Field(...)
    voltage_ub_inv: float = Field(...)
    voltage_uc_inv: float = Field(...)
    current_a_inv: float = Field(...)
    current_b_inv: float = Field(...)
    current_c_inv: float = Field(...)
    current_avg_inv: float = Field(...)
    frequency_inv: float = Field(...)
    cos_inv: float = Field(...)
    heat_sink_temp_inv: float = Field(...)
    energy: float = Field(...)
    state_1_inv: float = Field(...)
    state_2_inv: float = Field(...)


class Reading(ReadingBase):
    id: int